import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "leaflet/dist/leaflet.css";  // Importa los estilos de Leaflet
import "./globals.css";  // Asegúrate de que los estilos globales vengan después



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beacon Tracker",
  description: "Generated by Esteban Ortiz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
